# Generated by Django 4.1 on 2022-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('company', models.CharField(max_length=100)),
                ('over_18', models.BooleanField()),
                ('password', models.CharField(max_length=256)),
                ('private_pin', models.CharField(max_length=100)),
            ],
        ),
    ]
