# Generated by Django 4.1 on 2022-08-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_role',
        ),
    ]
