# Generated by Django 3.2.12 on 2022-08-11 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('website', models.URLField()),
                ('available_timeslots', models.CharField(default='', max_length=2048)),
                ('call_for_papers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('coordinates', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2048)),
                ('target_group', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('PR', 'Professional')], max_length=2)),
                ('available_timeslots', models.CharField(max_length=2048)),
                ('minimal_lecture_length', models.IntegerField()),
                ('maximal_lecture_length', models.IntegerField()),
                ('preferred_presentation_style', models.CharField(choices=[('RE', 'Recorded'), ('LI', 'Live')], max_length=2)),
                ('qualification_for_lecture', models.CharField(max_length=512)),
                ('questions_during_lecture', models.BooleanField()),
                ('questions_after_lecture', models.BooleanField()),
                ('additional_information_by_presentator', models.CharField(max_length=2048)),
                ('scheduled_presentation_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_presentation_length', models.IntegerField(default=0)),
                ('scheduled_presentation_style', models.CharField(choices=[('RE', 'Recorded'), ('LI', 'Live')], max_length=2)),
                ('further_information', models.CharField(max_length=2048)),
                ('related_website', models.URLField()),
                ('link_to_material', models.URLField()),
                ('link_to_recording', models.URLField()),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('presentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenting', to='auth.user')),
                ('scheduled_in_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_in', to='events.room')),
            ],
        ),
    ]
