# Generated by Django 4.1.2 on 2022-10-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='lecture',
            name='custom_question_answers',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
