# Generated by Django 3.2.12 on 2022-08-09 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('coordinates', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2048)),
                ('target_group', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('PR', 'Professional')], max_length=2)),
                ('available_timeslots', models.DateField()),
                ('minimal_lecture_length', models.IntegerField()),
                ('maximal_lecture_length', models.IntegerField()),
                ('preferred_presentation_style', models.CharField(choices=[('RE', 'Recorded'), ('LI', 'Live')], max_length=2)),
                ('qualification_for_lecture', models.CharField(max_length=512)),
                ('questions_during_lecture', models.BooleanField()),
                ('questions_after_lecture', models.BooleanField()),
                ('additional_information_by_presentator', models.CharField(max_length=2048)),
                ('scheduled_presentation_time', models.DateTimeField()),
                ('scheduled_presentation_length', models.IntegerField()),
                ('scheduled_presentation_style', models.CharField(choices=[('RE', 'Recorded'), ('LI', 'Live')], max_length=2)),
                ('further_information', models.CharField(max_length=2048)),
                ('related_website', models.URLField()),
                ('link_to_material', models.URLField()),
                ('link_to_recording', models.URLField()),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('presentators', models.ManyToManyField(related_name='presentating', to=settings.AUTH_USER_MODEL)),
                ('scheduled_in_rooms', models.ManyToManyField(to='events.Room')),
            ],
        ),
    ]
