# Generated by Django 4.1.2 on 2022-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_custom_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='disabled_fields',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
