# Generated by Django 3.2.12 on 2022-08-10 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220810_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='scheduled_presentation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
