# Generated by Django 3.2.12 on 2022-08-10 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_lecture_scheduled_presentation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='scheduled_presentation_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='scheduled_presentation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
