# Generated by Django 3.2.12 on 2022-08-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220810_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='presentators',
        ),
        migrations.AddField(
            model_name='lecture',
            name='presentator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenting', to='events.event'),
        ),
    ]
