# Generated by Django 3.2.12 on 2022-08-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20220810_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenting', to=settings.AUTH_USER_MODEL),
        ),
    ]
