# Generated by Django 3.2.12 on 2022-08-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_alter_lecture_presentator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenting', to='auth.user'),
        ),
    ]
