# Generated by Django 3.2.12 on 2022-08-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_lecture_presentator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='scheduled_in_rooms',
        ),
        migrations.AddField(
            model_name='lecture',
            name='scheduled_in_rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_in', to='events.room'),
        ),
    ]
