# Generated by Django 3.2.12 on 2022-08-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220811_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='scheduled_in_rooms',
            new_name='scheduled_in_room',
        ),
    ]
